# Aquarius - Automation Simplified
#
# @brief Git script for exporting PCB data for the repo.
# @note runs manually or automatically when there is a release
# @date 6/23/26
# @author cyberreefguru
# (c) CRG Makes 2026
name: Kibot-Sample-Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-export-pcb-latest:
    uses: ./.github/workflows/crgm-ecad-release.yaml
      name: 'Aquarius Client'
      repo-name: aquarius-client-hw
      file-name: aquarius-client-hw
      container-name: ghcr.io/inti-cmnb/kicad9_auto_full:latest
  call-export-pcb-907:
    uses: ./.github/workflows/crgm-ecad-release.yaml
    with:
      name: 'Aquarius Client'
      repo-name: aquarius-client-hw
      file-name: aquarius-client-hw
      container-name: ghcr.io/inti-cmnb/kicad9_auto_full:1.8.5